name: Test Build

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Validate recipes
      run: python3 scripts/validate-recipes.py
    
    - name: Update index
      run: python3 scripts/update-index.py
    
    - name: Build site
      run: python3 scripts/build.py
    
    - name: Verify build
      run: |
        if [ ! -f dist/index.html ]; then
          echo "Error: index.html not found in dist/"
          exit 1
        fi
        if [ ! -f dist/scripts/config.js ]; then
          echo "Error: config.js not found in dist/scripts/"
          exit 1
        fi
        echo "✅ Build verification passed!"
